### PR TITLE
Add Categories grid to Welcome page

### PR DESCRIPTION
**Pull request by mdsimpson42**
As requested by Polly, add the categories grid on to the welcome page. May need refinement, but we can do that in the New Year.

### CODE REVIEW

**Review by tomalrussell — APPROVED** [review]
Sure - looks like a clean code change, hopefully it’s clear to first time visitors what to do with those links.

**Review by matkoniecz — APPROVED** [review]
code looks nicer that I expected :)

**Comment by polly64** [comment]
@mdsimpson42 many thanks should it be visible on live landing page now?

**Comment by matkoniecz** [comment]
@polly64 It still needs to be merged (can be done by @tomalrussell or @mdsimpson42 ) and deployed (can be done also by me)

**Comment by mdsimpson42** [comment]
I've merged it, but I'm at my parents' house, and NUIT is still repairing my work laptop. @matkoniecz, if you can deploy it, that'd be great. Or I can do it when I get back to Newcastle, but that probably won't be until Monday now.

**Comment by matkoniecz** [comment]
I can deploy it, especially as it requires updating staging to have both this and general planning work.

**Pull request merged**
