### PR TITLE
Enable hiding legend also on a large screens

### PR DESCRIPTION
**Pull request by matkoniecz**

### CODE REVIEW

**Comment by edwardchalstrey1** [comment]
Hey @matkoniecz it looks like right now if I wanted to merge your PR I can't do that currently - could you request my review and I'll see if that allows me to do it, or otherwise I may need my permissions updated

**Comment by matkoniecz** [comment]
@edwardchalstrey1 I cannot even reqest review from you - apparently you need a commit rights here.

**Comment by tomalrussell** [comment]
Hi @edwardchalstrey1 you should have an invite to the colouring-cities organisation - might be in your email/GitHub notifications/at this link: https://github.com/orgs/colouring-cities/invitations/

**Comment by edwardchalstrey1** [comment]
Thx @tomalrussell I have access now

**Pull request merged**
