### PR TITLE
set message about planned layer to yellow

### PR DESCRIPTION
**Pull request by matkoniecz**
for conistency with other similar boxes

### CODE REVIEW

**Comment by matkoniecz** [comment]
screen

**Comment by polly64** [comment]
@matkoniecz what are you using this one for?

**Comment by polly64** [comment]
@matkoniecz would be good to be consistent based on planning colours and  then change other ones. So pink button brings layer up, blue button provides background . Pale grey with italics is disclaimer . We used yellow for 'not yet activated' but we could just use greyed out

**Comment by matkoniecz** [comment]
> what are you using this one for?

I do not understand the question here

**Comment by mdsimpson42** [comment]
@polly64 @matkoniecz Do we have approval for the colours etc. here? Or are you still discussing it?

**Comment by matkoniecz** [comment]
this one was discussed at the meeting and yes, it should be yellow

**Comment by polly64** [comment]
@mdsimpson42 @matkoniecz . Mateussz shouldn't it be blue because Explanatory info?

blue button provides background . Pale grey with italics is disclaimer . We used yellow for 'not yet activated' but we could just use greyed out

**Comment by polly64** [comment]
ah ok

**Pull request merged**
