### PR TITLE
Various tweaks requested by Polly

### PR DESCRIPTION
**Pull request by mdsimpson42**
Changes to subcategories, wording and typo fixes discussed in a meeting with Polly on 02/02. #1074

### CODE REVIEW

**Comment by mdsimpson42** [comment]
@matkoniecz can you approve this, please?

**Review by matkoniecz — APPROVED** [review]
though I have not actually run this code

**Comment by polly64** [comment]
@matkoniecz should I see all Mike's minor changes from this morning activated on Colouring London now?

**Comment by matkoniecz** [comment]
no, Mike needs to merge this first

**Comment by matkoniecz** [comment]
Unless you mean other already merged ones? Then I deployed this changes to the production server.

**Pull request merged**
